# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-05 19:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nash', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='user_id',
            new_name='user_name',
        ),
        migrations.AlterField(
            model_name='users',
            name='password',
            field=models.CharField(max_length=30),
        ),
    ]
